### ISSUE TITLE
[Serafin parser] Support double precision and variables names

### ISSUE THREAD

**Issue by lucduron** [CNR-Engineering/telemac_toolbox#1]
Improve Serafin (slf/Serafin.py) parser to :
* support double precision slf files (SERAFIND format)
* use abbrevation list of slf/data/Serafin_{3,2}D.csv for known variables (common Telemac variables), and use exact variable name for unknown variables (user defined variables)
* recognize english variable names => each script reading/writing slf files should have a new argument `--lang` whose default value is `fr`

**Comment by Helio-Wang** [comment]
Can you provide test .slf files for the first & third improvements ?

**Comment by lucduron** [comment]
Find attached two result files with SERAFIN and SERAFIND file format : [r2d_malpasset-small.zip](https://github.com/CNR-Engineering/PyTelTools/files/941776/r2d_malpasset-small.zip).

**Comment by Helio-Wang** [comment]
SERAFIND format is now supported since commit 58b2e36ec9216a2bea1cb0c42f710be8790a32ef
